### PR TITLE
Feature/start code

### PR DESCRIPTION
**Pull request by supertoto29**
**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Completed the functions for the new backplane power

## How has this been tested ?
Vscode build is complete
Test to be done on a dev board before merging to master

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by 0x72D0** [comment]
maybe the INA226 library can be implemented as a library and not by copying all the files inside the project?

**Comment by supertoto29** [comment]
Yes It could be done. We can include the TC74A5 at the same time. We should put them in hardware utility?

**Comment by 0x72D0** [comment]
yes every chip library should be put in hardware utility.

**Comment by supertoto29** [comment]
I have put the utility and TC74A5 in the hardware utility. I am going to clean up the code on the other repo.
INA226 has been included as a platformio librairy

Ready to review @0x72D0

**Review by 0x72D0 — DISMISSED** [review]
LGTM!

**Comment by supertoto29** [comment]
@0x72D0 
Did some fix for hardware-utility changes

**Review by 0x72D0 — APPROVED** [review]
LGTM!

**Pull request merged**
